/**
 * Prisma Seed Script
 *
 * This runs automatically when you execute:
 *   - npx prisma migrate reset  (resets DB then seeds)
 *   - npm run db:seed            (seeds only)
 *
 * It reads from prisma/seeds/breeds.json which is generated by:
 *   npx ts-node scripts/translate-breeds.ts
 *
 * IMPORTANT: Commit prisma/seeds/breeds.json to git so this works
 * without needing internet access to Cat/Dog API or Gemini.
 */

import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';
import * as fs from 'fs';
import * as path from 'path';
import 'dotenv/config';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function seedBreeds() {
  const seedFilePath = path.join(__dirname, 'seeds', 'breeds.json');

  if (!fs.existsSync(seedFilePath)) {
    console.warn(
      '⚠ prisma/seeds/breeds.json not found. Skipping breed seed.\n' +
        '  Run: npx ts-node scripts/translate-breeds.ts  to generate it.',
    );
    return 0;
  }

  const breeds: any[] = JSON.parse(fs.readFileSync(seedFilePath, 'utf-8'));
  console.log(`🌱 Seeding ${breeds.length} breeds from breeds.json...`);

  let count = 0;
  for (const breed of breeds) {
    await prisma.breed.upsert({
      where: { id: breed.id },
      create: {
        id: breed.id,
        petType: breed.petType,
        nameEn: breed.nameEn,
        descriptionEn: breed.descriptionEn ?? null,
        temperamentEn: breed.temperamentEn ?? null,
        originEn: breed.originEn ?? null,
        nameVi: breed.nameVi ?? null,
        descriptionVi: breed.descriptionVi ?? null,
        temperamentVi: breed.temperamentVi ?? null,
        originVi: breed.originVi ?? null,
        lifeSpan: breed.lifeSpan ?? null,
        weightKg: breed.weightKg ?? null,
        imageUrl: breed.imageUrl ?? null,
        wikipediaUrl: breed.wikipediaUrl ?? null,
        isTranslated: breed.isTranslated ?? false,
      },
      update: {
        nameVi: breed.nameVi ?? null,
        descriptionVi: breed.descriptionVi ?? null,
        temperamentVi: breed.temperamentVi ?? null,
        originVi: breed.originVi ?? null,
        isTranslated: breed.isTranslated ?? false,
      },
    });
    count++;
  }

  return count;
}

async function main() {
  console.log('🚀 Running Pawdar database seed...\n');

  const breedCount = await seedBreeds();

  if (breedCount > 0) {
    console.log(`✅ Seeded ${breedCount} breeds successfully`);
  }

  console.log('\n🎉 Database seed complete!');
}

main()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
